name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available

      - name: Change wrapper permissions
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload artifact (for SonarCloud)
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: app/build/reports/tests/testDebugUnitTest/index.html

      - name: Save PR number (for SonarCloud)
        if: github.event_name == 'pull_request'
        run: echo ${{ github.event.number }} > PR_NUMBER.txt

      - name: Upload PR number to GitHub Artifacts (for SonarCloud)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: PR_NUMBER
          path: PR_NUMBER.txt